=== Yacineos/tuxLetterGameL3MIAGE/src/xsd/profil.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://myGame/tux"
           elementFormDefault="qualified">
    <!-- inclure les fichiers de dépendances-->
    <xs:include schemaLocation="dico.xsd"/> 
    
    
    <!-- déclaration des instances -->
    <xs:element name="profil" type="Profil" />
    
    
    
    <!-- définition du type Profil-->
    <xs:complexType name="Profil">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <!-- on peut définir un type pour restreindre le type à des .jpg-->
            <xs:element name="avatar" type="xs:string"/>
            <xs:element name="anniversaire" type="xs:date"/>
            <xs:element name="parties" type="Parties"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Parties">
        <xs:sequence>
            <xs:element name="partie" type="Partie" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="temps" type="xs:double" minOccurs="0"/>
            <xs:element name="mot" type="Mot"/>
            <xs:element name="niveau" type="Niveau" />
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required"/> 
        <xs:attribute name="trouvé" type="xs:string"/> 
    </xs:complexType>
    
</xs:schema>

=== Yacineos/tuxLetterGameL3MIAGE/src/xml/profil.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--
    Document   : save_example.xml.xml
    Created on : August 31, 2014, 3:31 PM
    Author     : Johan Sarrazin / Céline Fouard / Nicolas Glade
    Description:
        Purpose of the document follows.
-->

<profil xmlns="http://myGame/tux" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://myGame/tux ../xsd/profil.xsd" >
    <nom>Alban</nom>
    <avatar>conan.jpg</avatar>
    <anniversaire>2006-05-08</anniversaire>
    <parties>
        <partie date="2013-12-10">
            <temps>20.0</temps>
            <mot>cle</mot>
            <niveau>1</niveau>
        </partie>
        <partie date="2013-12-11" trouvé="75%">
            <mot>indice</mot>
            <niveau>2</niveau>
        </partie>
        <partie date="2013-12-11">
            <temps>20.0</temps>
            <mot>hustlers</mot>
            <niveau>3</niveau>
        </partie>
    </parties>
</profil>

=== Yacineos/tuxLetterGameL3MIAGE/src/xml/profil2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>


<profil xmlns="http://myGame/tux" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://myGame/tux ../xsd/profil.xsd" >
    <nom>Tristan</nom>
    <avatar>lada.jpg</avatar>
    <anniversaire>2001-09-11</anniversaire>
    <parties>
        <partie date="2023-10-10">
            <temps>30.0</temps>
            <mot>booz</mot>
            <niveau>1</niveau>
        </partie>
        <partie date="2023-09-11" trouvÃ©="55%">
            <mot>aikido</mot>
            <niveau>2</niveau>
        </partie>
        <partie date="2013-09-29">
            <temps>15.0</temps>
            <mot>hustelmania</mot>
            <niveau>4</niveau>
        </partie>
    </parties>
</profil>
